# Generated by Django 3.0.2 on 2020-04-04 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200404_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_slug',
            field=models.CharField(default=1, max_length=210),
        ),
    ]
